name: nats
services:
  nats-service:
    image: nats:latest
    container_name: nats-service
    ports:
      - "4222:4222"
      - "8222:8222"
    command: ["-js"]
    volumes:
      - ./nats_data:/data
    environment:
      - NATS_SERVER_NAME=nats-service
      - NATS_HTTP_PORT=8222